global:
  scrape_interval: 10s
  scrape_timeout: 5s

rule_files:

scrape_configs:
  - job_name: "web-create"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:30002"]

  - job_name: "web-read"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:30003"]

  - job_name: "web-update"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:30004"]

  - job_name: "web-delete"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:30005"]

  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:8081"]