apiVersion: v1
kind: Service
metadata:
  name: fiap-4-service-delete
spec:
  type: NodePort
  selector:
    app: delete-contacts-pod
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30005