apiVersion: v1
kind: Service
metadata:
  name: fiap-4-service-update
spec:
  type: NodePort
  selector:
    app: update-contacts-deployment
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30004