apiVersion: v1
kind: Service
metadata:
  name: fiap-4-service-read
spec:
  type: NodePort
  selector:
    app: read-contacts-deployment
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30003